apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-schedule-deployment
  namespace: kubernetes-cluster
  labels:
    app: class-schedule
spec:
  # Rolling Update Strategy is defined by default, see note below
  replicas: 3 # Run 3 instances of your application
  selector:
    matchLabels:
      app: class-schedule
  template:
    metadata:
      labels:
        app: class-schedule
    spec:
      containers:
      - name: class-schedule-container
        image: biprob/class-schedule:latest
        ports:
        - containerPort: 5000 
        env:
        # Load environment variables from a Kubernetes Secret (best practice)
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: class-schedule-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: class-schedule-secret
              key: db_pass
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: class-schedule-secret
              key: jwt_secret
        # You can pass PORT directly as it's not sensitive
        - name: PORT
          value: "5000"