apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-schedule-deployment
  namespace: kubernetes-cluster
  labels:
    app: class-schedule
spec:
  # Run 2 instances of the application
  replicas: 2
  selector:
    matchLabels:
      app: class-schedule
  template:
    metadata:
      labels:
        app: class-schedule
    spec:
      containers:
      - name: class-schedule
        # Use your built image
        image: biprob/class-schedule:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 # The port your Node.js app runs on

        # --- Environment Variables (DB_USER, DB_PASS) ---
        # NOTE: It's best practice to use Kubernetes Secrets for passwords (DB_PASS)
        env:
        - name: DB_USER
          value: "bipro"
        - name: DB_PASS
          value: "bipro"
        # --- End Environment Variables ---