apiVersion: v1
kind: Service
metadata:
  name: class-schedule-service
  namespace: kubernetes-cluster
  labels:
    app: class-schedule
spec:
  # Selects the pods created by the deployment
  selector:
    app: class-schedule
  ports:
  - name: http
    port: 5000         # Port the service listens on (internal cluster port)
    targetPort: 5000 # Port on the container (where the app is running)
    nodePort: 30005  # Port exposed on each cluster node (for external access)
  type: NodePort